spring.application.name=application-management-system


spring.datasource.url=jdbc:postgresql://localhost:5432/sup

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=Suppi@123

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE CONFIGURATION
# ===============================

# Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatically create/update tables (options: none, validate, update, create, create-drop)
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console
spring.jpa.show-sql=true